### ISSUE TITLE
Opening settings app and "going back" freezes watch

### ISSUE THREAD

**Issue by WalaWala** [jeffmer/JeffsBangleAppsDev#2]
When you open the settings and close it right after that the watch freezes. Sometimes the clock is displayed (and time moves on), but most of the time the display is just black and no buttons work until reboot.
When the clock is displayed the buttons don't work as well.

**Comment by jeffmer** [comment]
Try pressing and holding Button 3. If there are notifications waiting, there is a race condition that sometimes freezes the watch. Best to clear your iPhone notifications in the iPhone notification centre before starting. After that notifications are cleared when you press OK so it does not happen.

**Comment by WalaWala** [comment]
Deleting the notifications did help a bit, but only so that it works in 2 out of 3 tries...

**Comment by jeffmer** [comment]
I do not have any problems switching between clock and settings as long as I do not turn the ANCS widget on or off. 

When ANCS is turned off, the iPhone tries to reconnect and seems to crash the bluetooth firmware when you switch out of settings. If you turn iPhone bluetooth off or forget the Bangle pairing it does not happen.

**Comment by WalaWala** [comment]
For me it's still crashing when I simply open the settings app and go back. Are there some kind of debug logs I can access?

**Comment by jeffmer** [comment]
Here are a few things to try:
1) I have put the exact version of the firmware that I have on my Bangle - ...bangle’js new.zip in the repository.
2) I have pretokenize set on all my uploads - so both servings. clocks and the widget are tokenised. The switch is in the app loader under other. 
3) Does it crash when you switch off bluetooth in your phone before switching?

**Comment by WalaWala** [comment]
1. I've just flashed that version, no change at all
2. Seems to help (haven't had that on until now, still new to this watch)
3. Seems to help as well, but I think I'll stick to No. 2

**Comment by jeffmer** [comment]
If 2 helps it’s probably a low memory issue - remove some other widgets. 
 3 should not be necessary.
