### ISSUE TITLE
What changed in espruino

### ISSUE THREAD

**Issue by abhigkar** [jeffmer/JeffsBangleAppsDev#4]
Great work!!

Just wanted to know if your custom change is merged in espruino master? And what are your changes? You said that it will work with the standard espruino? after installing and enabling the ANCS widget I am not able to see a any icon and iPhone is also not scanning BangleJS.

Any clue??

**Comment by abhigkar** [comment]
Ok, seems I totally missed that information that it will work only a set of app. I tried with Multi clock and I am able to see the little phone icon in widget area. It always stay in white colour. 

My iPhone is connected to watch but no free icon. Also when connected from phone, I cannot see any pairing prompt. 

Using iPhone 6 iOS 12.4.8.

**Comment by jeffmer** [comment]
As you noted, the widget only works with compatible apps such as Multiclock. Now you have the icon:

If your iPhone is already paired with the Bangle you need to :

1) Turn off the Bangle in Settings

2) Forget the device on the iPhone. 

3) reboot the Bangle by pressing button 1 and then pair with iPhone as per instructions.

**Comment by jeffmer** [comment]
> Great work!!
> 
> Just wanted to know if your custom change is merged in espruino master? And what are your changes? You said that it will work with the standard espruino? after installing and enabling the ANCS widget I am not able to see a any icon and iPhone is also not scanning BangleJS.
> 
> Any clue??
