### ISSUE TITLE
Desktop Launcher app: cyclic scrolling and focus

### ISSUE THREAD

**Issue by zloid** [jeffmer/JeffsBangleAppsDev#6]
Hello! Thanks for the Desktop Launcher app!

Could you please add a cyclic scrolling of screens with applications for -Desktop Launcher-? Now you can scroll either forward or backward. Swipe left or right hits a dead end.

It will be like this: (1/4), swipe ->, (4/4)
It will be like this: (4/4), swipe <-, (1/4)
 
And it would also be great if at the start of the launcher there would immediately be a focus on the first application from the top left. Now you need to additionally click on the button or make a swipe so that the focus appears on the first application from the top left, and only then you can launch the application.

**Comment by jeffmer** [comment]
Now implemented this as well. Thanks again. 

Try it at https://jeffmer.github.io/BangleApps

Jeff

**Comment by zloid** [comment]
Great! Really useful app ;)
