### ISSUE TITLE
Multi Clock: pinning only one clock face

### ISSUE THREAD

**Issue by zloid** [jeffmer/JeffsBangleAppsDev#7]
Multi Clock is a nice app! But now we cannot pinned only one clock face. Could you please add this feature?
Now, when you start the launcher, the selected clock face is reset every time.

Kind regards, Sergey

**Comment by jeffmer** [comment]
Thanks for the feedback and suggestion.  

I have now implemented this. You can try it at https://jeffmer.github.io/BangleApps
before I submit it to the espruino rep

Jeff

**Comment by zloid** [comment]
Working well, thanks! :)
