### ISSUE TITLE
why is it only in 24 hour time?

### ISSUE THREAD

**Issue by superpotato9** [jeffmer/JeffsBangleAppsDev#9]
i was wondering why the watch is only in 24 hour time and if i can easily add something like an IF function to make all of the faces 12 hour time (eg. if hour_Time > 12: hour_Time - 12)

**Comment by jeffmer** [comment]
I have not looked into it as I prefer 24 hr format but gave a look at one of Gordon’s clocks in the official repository that take notice of the 12/24 hour format in settings under locale if you want to implement it.

**Comment by superpotato9** [comment]
ok thanks i will look into it
